### ISSUE TITLE
`monokle validate` tries to parse Helm syntax as YAML

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle-cli#24]
First observed by these warnings in the terminal. We already put the log level of the YAML parser on silent but the underlying problem remains. It appears that Helm files get parsed as YAML while this is a templating language and thus is incorrect.

![image (12)](https://github.com/kubeshop/monokle-cli/assets/7761005/ae6a4a9e-5f56-480f-be2d-4cd062519613)

**Comment by olensmar** [comment]
yeah I've seen this also - need to look at how desktop handles this..

**Comment by f1ames** [comment]
Handling helm files could be a part of `@monokle/parser` package.

We have similar logic in Cloud to filter such files - https://github.com/kubeshop/monokle-saas/blob/c14f1c6f3bc524aa00a844016e6960f3517d8fa8/clientDomain/web/src/utils/yaml.ts#L13-L28.

And in Desktop it is more generic, filtering based on parser errors - https://github.com/kubeshop/monokle/blob/61b22b835dd336bcd648362950e84d7504a3d1f1/src/redux/services/resource.ts#L306-L313:

![image](https://github.com/kubeshop/monokle-cli/assets/1061942/c161bce0-bb62-4e0b-9cf8-5ec259dc67d3)

It would be good for parser to be able to recognize helm files as Cloud does.

**Comment by f1ames** [comment]
Interestingly it only happens when I run monokle CLI installed through `npm i -g`, if I run local build (or even package) there is no such warnings, so it will be more cumbersome to verify 🤔 But https://github.com/kubeshop/monokle-core/pull/516 should do the job.

**Comment by WitoDelnat** [comment]
FYI, the binary I installed from brew also has the problem, that is where I initially discovered the problem.
