### ISSUE TITLE
Add default Kubernetes version when using `monokle init`

### ISSUE THREAD

**Issue by WitoDelnat** [kubeshop/monokle-cli#30]
More a nice to have, but you currently manually have to type the Kubernetes version and it would be nice if the default value was "latest" which would do a fetch call to get the latest K8s version.

```
code/monokle/monokle-demo  ▶ monokle init  
✔ Add your Kubernetes version (e.g. 1.27.1) … 1.27.1
✔ Choose frameworks › Baseline Pod Security Standard, Restricted Pod Security Standard
```

**Comment by f1ames** [comment]
This was already fixed in https://github.com/kubeshop/monokle-cli/pull/32.
